name: ğŸš€ Deploy to Railway

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Kodingizni nusxalash
      uses: actions/checkout@v3

    - name: ğŸ› ï¸ Railway CLI install & deploy
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        railway login --service-token ${{ secrets.RAILWAY_TOKEN }}
        railway up
